### ISSUE TITLE
groupPodutcs() yeilds bad results when passed a list longer than one

### ISSUE THREAD

**Issue by FJ-RATO** [FJ-RATO/Adentis_Challenge_Scala#8]
Detected when running the assert
`assert(Main.groupProduct(List(order0,order1,order2)) == List[(String, Int)](("1-3 months", 7), ("4-6 months", 3), ("7-12 months", 3), (">12 months", 5)))`

Expected output:
`List((1-3 months,7), (4-6 months,3), (7-12 months,3), (>12 months,5))`

Current output:
`List((1-3 months,10), (4-6 months,10), (7-12 months,12), (>12 months,18))`

**Note**

- The list only has 18 products distributed along 3 orders
- The output is surpassing the existing elements

Probably something with the loop

**Comment by birdofartemis** [comment]
`val accMore12 = older12 + order.products.count(product => product.date.isBefore(filters(0)))`
`grouper(..., older12 + accMore12, ...)`

Why are you doing this sum two times?

**Comment by FJ-RATO** [comment]
Because I got distracted, it solved the problem.
Closing the issue, thx for the help
